# permissions for end users to edit codeprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: codeproject-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: proj
    app.kubernetes.io/part-of: proj
    app.kubernetes.io/managed-by: kustomize
  name: codeproject-editor-role
rules:
- apiGroups:
  - proj.zachfi
  resources:
  - codeprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proj.zachfi
  resources:
  - codeprojects/status
  verbs:
  - get
