---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - proj.zachfi
  resources:
  - codeprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proj.zachfi
  resources:
  - codeprojects/finalizers
  verbs:
  - update
- apiGroups:
  - proj.zachfi
  resources:
  - codeprojects/status
  verbs:
  - get
  - patch
  - update
